config/routes.rb
SpeedingTicketNew::Application.routes.draw do

  resources :purchases

	root to: 'tickets#index'
	
	get 'signup', to: 'technicians#new', as: 'signup'
	get 'login', to: 'sessions#new', as: 'login'
	get 'logout', to: 'sessions#destroy', as: 'logout'

  	resources :technicians
  	resources :sessions
  	resources :users do
  		resources :comments
  	end
  	resources :assets do
  		resources :comments
  	end
  	resources :tickets do
  		resources :comments
  	end
  	resources :purchases
  	resources :softwares

end

app/models/user.rb
class User < ActiveRecord::Base

#Associations
	has_many :assets 
	has_many :tickets
	has_many :purchases
	has_many :comments, as: :commentable

#Validation
	validates_presence_of :first_name, :last_name, :email, :location, :department
	validates_uniqueness_of :email
	validates :email, :email => true
	validates :phone_number, :length => { :minimum => 6, :maximum => 12 }, :allow_blank => true

#Attachments	
    has_attached_file :avatar, :styles => { :medium => "100x100>", :thumb => "32x32>" }, :default_url => "/images/:style/missing.png"
    
#Definitions
	DEPARTMENT = ['ADPR', 'BCS', 'COMM', 'CSD', 'DEAN', 'JRN', 'TISM' ]
    
#Functions
  def full_name
		[first_name, last_name].join(' ')
	end
	
	def self.search(search)
  	if search
   	 User.where('first_name LIKE ? OR last_name LIKE ? OR email LIKE ? OR location LIKE ? OR phone_number LIKE ? OR department LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
	 	else
    	scoped
		end
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :authorize, only: [:new, :create, :show, :edit, :update, :index]

#New Action
	def new
		@user = User.new
	end

#Create Action	
	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to @user
		else
			render "new"
		end
	end

#Show Action	
	def show
    	@user = User.find(params[:id])
    	@commentable = @user
    	@comments = @commentable.comments
    	@comment = Comment.new
	end

#Edit Action	
	def edit
    	@user = User.find(params[:id])
	end

#Update Action	
	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			redirect_to @user
		else
			render "edit"
		end
	end

#Index Action	
	def index
		@user_list = User.all.search(params[:search])
	end
	
#Private Actions	
private	
	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :location, :phone_number, :department, :avatar)
    end
	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<div class="list-group-item list-group-item-hover">
	<%= link_to user_path(user) do %>
		<div class="row">
			<div class="col-md-1">
				<%= image_tag user.avatar.url(:thumb), :class => 'img-circle border' %>
			</div>
			<div class="col-md-4">
				<strong><%= user.full_name %> (<%= user.email %>)</strong>
				<br>
				<%= user.location %> | <%= user.phone_number %> | <%= user.department %>
			</div>
		</div>
	<% end %>
</div>

app/views/users/_user_form.html.erb
<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div id='errorExplaination'>
			<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
			<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
	
	<div class="row">
		<div class="col-md-3">
			<%= f.label :first_name, "First Name" %>
			<br>
			<%= f.text_field :first_name, :class => 'form-control' %>
		</div>
		<div class="col-md-3">
			<%= f.label :last_name, "Last Name" %>
			<br>
			<%= f.text_field :last_name, :class => 'form-control' %>
		</div>
	</div>
	
	<div class="row">&nbsp;</div>
	
	<div class="row">
		<div class="col-md-3">
			<%= f.label :email, "Email" %>
			<br>
			<%= f.text_field :email, :class => 'form-control' %>
		</div>
	</div>
	
	<div class="row">&nbsp;</div>
	
	<div class="row">
		<div class="col-md-3">
			<%= f.label :location, "Location" %> <span class="example">(example: CAS ###)</span>
			<br>
			<%= f.text_field :location, :class => 'form-control' %>
		</div>
	</div>
		
	<div class="row">&nbsp;</div>
	
	<div class="row">
		<div class="col-md-3">
			<%= f.label :phone_number, "Phone Number" %>
			<br>
			<%= f.text_field :phone_number, :class => 'form-control' %>
		</div>
	</div>
	
	<div class="row">&nbsp;</div>
	
	<div class="row">
		<div class="col-md-3">
			<%= f.label :department, "Department" %>
			<br>
			<%= f.select(:department, User::DEPARTMENT) %>
		</div>
	</div>
	
	<div class="row">&nbsp;</div>
	
	<div class="row">
		<% if @user.avatar %>
			<div class="col-md-1">
				<%= image_tag @user.avatar.url(:thumb), :class => 'img-circle border' %>
			</div>
		<% end %>
		<div class="col-md-3">
			<%= f.label :avatar, "Upload an Avatar" %>
			<br>
			<%= f.file_field :avatar %>
		</div>
	</div>
	
	<div class="row">&nbsp;</div>
	
	<div class="row">
		<div class="col-md-3">
			<%= f.submit "Save User", :class => 'btn btn-success' %>
		</div>
	</div>

<% end %>

<div class="row">&nbsp;</div>
<div class="row">&nbsp;</div>

app/views/users/_user_purchases.html.erb
<div class="row">
	<div class="col-md-1">
		<%= image_tag @purchase.user.avatar.url(:thumb), :class => 'img-circle border' %>
	</div>
	<div class="col-md-4">
		<strong><%= @purchase.user.full_name %> (<%= @purchase.user.email %>)</strong>
		<br>
		<%= @purchase.user.location %> | <%= @purchase.user.phone_number %> | <%= @purchase.user.department %>
	</div>
</div>

app/views/users/_user_tickets.html.erb
<div class="row user">
	<div class="col-md-1">
		<%= image_tag @ticket.user.avatar.url(:thumb), :class => 'img-circle border' %>
	</div>
	<div class="col-md-4">
		<strong><%= @ticket.user.full_name %> (<%= @ticket.user.email %>)</strong>
		<br>
		<%= @ticket.user.location %> | <%= @ticket.user.phone_number %> | <%= @ticket.user.department %>
	</div>
</div>

app/views/users/edit.html.erb
<h3 class="page-title"> Edit <%= @user.full_name %> </h3>

<%= render "user_form" %>

<div class="row col-md-12">
	<%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> back'.html_safe, user_url(@user) %>
</div>

app/views/users/index.html.erb
<h2> Communication Arts & Sciences Users </h2>

<div class="list-group-item list-group-item-set-height">
	<%= form_tag users_path, :method => 'get', :id => "users_search" do %>
		<%= text_field_tag :search, params[:search], :autocomplete => 'off', :placeholder => 'Search Users...' %>
  <div class="pull-right"><%= link_to '<span class="glyphicon glyphicon-plus-sign add-ticket"></span>'.html_safe, new_user_path %></div>    	
</div>

<div id="users">
	<% @user_list.order('last_name ASC').each do |user| %>
		<%= render "user", :user => user  %>
	<% end %>
</div>
<% end %>

app/views/users/index.js.erb
$("#users").html('<%= j render(@user_list) %>');

app/views/users/new.html.erb
<h3 class="page-title"> New User </h3>

<%= render "user_form" %>

<div class="row col-md-12">
	<%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> back'.html_safe, users_url %>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-md-2">
		<%= image_tag @user.avatar.url(:medium), :class => 'img-circle border' %>
	</div>
	<div class="col-md-10 user-info">
		<strong><%= @user.full_name %> (<%= @user.email %>)</strong>
		<br>
		<%= @user.location %> | <%= @user.phone_number %> | <%= @user.department %>
		<br>
		<%= link_to 'Edit User', edit_user_path(@user), :class => 'btn btn-default btn-xs' %>
	</div>
</div>

<hr class="user-hr">

<% if @user.assets.present? %>
	<h4>Assets:</h4>
	<% @user.assets.each do |asset| %>
		<%= render "assets/asset_tickets", :asset => asset  %><br>	
	<% end %>
	
	<hr class="user-hr">
<% end %>

<% if @user.purchases.present? %>	
	<h4>Purchases:</h4>	
	<% @user.purchases.each do |purchase| %>
		<ul>
			<% if purchase.item_name and purchase.software.nil? %>
				<li><strong><%= purchase.item_name %></strong> on account <%= purchase.account_number %></li>
			<% end %>
			<% if purchase.software %>
				<li><strong><%= purchase.software.title %></strong> on account <%= purchase.account_number %></li>
			<% end %>
		</ul>
	<% end %>
<% end %>
	
	
<div class="row col-md-12 back-btn">
	<%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> back'.html_safe, users_url %>
</div>	
	
<div class="row col-md-12 description">Comments:</div>
<div class="row">&nbsp;</div>
	<%= render "comments/form" %>
<div class="row">
	<div class="col-md-9">&nbsp;</div>
</div>
	<%= render "comments/comments" %>