config/routes.rb
SpeedingTicketNew::Application.routes.draw do

  resources :purchases

	root to: 'tickets#index'
	
	get 'signup', to: 'technicians#new', as: 'signup'
	get 'login', to: 'sessions#new', as: 'login'
	get 'logout', to: 'sessions#destroy', as: 'logout'

  	resources :technicians
  	resources :sessions
  	resources :users do
  		resources :comments
  	end
  	resources :assets do
  		resources :comments
  	end
  	resources :tickets do
  		resources :comments
  	end
  	resources :purchases
  	resources :softwares

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base

#Asssociations
	belongs_to :user 
	has_many :assignments
	has_many :technicians, :through => :assignments
	has_many :attachments
	has_many :assets, :through => :attachments
	has_many :comments, as: :commentable

#Validation
	validates_presence_of :description

#Definitions
	TICKET_STATUS = ['not started', 'in progress', 'parts hold', 'client wait', 'done']
	
#Methods
	def user_email
  	user.try(:email)
	end

	def user_email=(email)
 	 self.user = User.find_by_email(email) if email.present?
 	end

 	def self.search(search)
  	if search
   	 Ticket.joins(:user).where('title LIKE ? OR description LIKE ? OR users.first_name LIKE ? OR users.last_name LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
	 	else
    	scoped
		end
	end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

	before_filter :authorize, only: [:new, :create, :show, :edit, :update, :index]

#New Action
	def new
		@ticket = Ticket.new
	end
	
#Create Action	
	def create
		@ticket = Ticket.new(ticket_params)
		if @ticket.save
			redirect_to @ticket
		else
			render "new"
		end
	end

#Show Action	
	def show
    	@ticket = Ticket.find(params[:id])
    	@commentable = @ticket
    	@comments = @commentable.comments
    	@comment = Comment.new
	end

#Edit Action	
	def edit
    	@ticket = Ticket.find(params[:id])
	end

#Update Action	
	def update
		@ticket = Ticket.find(params[:id])
		if @ticket.update_attributes(ticket_params)
			redirect_to @ticket
		else
			render "edit"
		end
	end
	
#Index Action
	def index
		@my_tickets = @current_technician.tickets.where.not(:status => 'done').search(params[:search]).order("created_at DESC")
		@active_tickets = Ticket.where.not(:status => 'done').search(params[:search]).order("created_at DESC")
		@inactive_tickets = Ticket.where(:status => 'done').search(params[:search]).page(params[:page]).per_page(25).order("created_at DESC")
		@new_tickets = @active_tickets.where(:technicians_count => 0)
	end
	
#Private Actions	
private	
	def ticket_params
		params.require(:ticket).permit(:user_id, :asset_id, :title, :description, :status, :deadline, :priority, {:technician_ids => []}, {:asset_ids => []}, :user_email)
    end
	
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_ticket.html.erb
<div class="list-group-item list-group-item-hover">
	<%= link_to ticket_path(ticket) do %>	
		<div class="row">
			<div class="col-md-1 ticket-id">
				<% if ticket.id < 10 %>
				  00<%= ticket.id %>
				<% elsif ticket.id >= 10 and ticket.id < 100 %>
					0<%= ticket.id %>
				<% else %>
					<%= ticket.id %>
				<% end %>
			</div>
			<div class="col-md-3">
				<span class="lead smaller"><%= ticket.user.full_name if ticket.user %></span><br>
				<small><%= ticket.title %></small>
			</div>
			<div class="col-md-2">
			<% if ticket.technicians.count <= 4 %>
				<% ticket.technicians.each do |technician| %>
					<%= image_tag technician.avatar.url(:thumb), :class => 'img-circle border pull-right' %>
				<% end %>
			<% else %>
				<span class="img-circle border pull-right additonal-techs">+<%= ticket.technicians.count - 3 %></span>
				<% ticket.technicians.first(3).each do |technician| %>
					<%= image_tag technician.avatar.url(:thumb), :class => 'img-circle border pull-right' %>
				<% end %>
			<% end %>
			</div>
			<div class="col-md-1">
				<% if ticket.status == "not started" %>
					<span class="label label-danger label-placement"><%= ticket.status %></span>
				<% elsif ticket.status == "in progress" %>
					<span class="label label-success label-placement"><%= ticket.status %></span>
				<% elsif ticket.status == "parts hold" %>
					<span class="label label-info label-placement"><%= ticket.status %></span>
				<% elsif ticket.status == "client wait" %>
					<span class="label label-primary label-placement"><%= ticket.status %></span>
				<% elsif ticket.status == "done" %>
					<span class="label label-default label-placement"><%= ticket.status %></span>
				<% end %>
			</div>
			<div class="col-md-2">
				Created:<br>
				<%= ticket.created_at.to_s(:short) %>
			</div>
			<div class="col-md-2">
				Deadline:<br>
				<% if ticket.deadline.nil? %>
					--
				<% else %>
					<%= ticket.deadline.to_s(:short) %>
				<% end %>
			</div>
			<div class="col-md-1 priority">
				<% if ticket.priority == true %>!<% end %>
			</div>
		</div>
	<% end %>
</div>

app/views/tickets/_ticket_form.html.erb
<%= form_for @ticket do |f| %>
	<% if @ticket.errors.any? %>
		<div id='errorExplaination'>
			<h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>
			<ul>
			<% @ticket.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
	
	<div class="row">
		<div class="col-md-1">
			<%= f.label :title, "Title" %>
		</div>
		<div class="col-md-5">
			<%= f.text_field :title, :class => 'form-control' %>
		</div>
		
		<div class="col-md-1 col-md-offset-1">
			<%= f.label :technician_id, "Technician(s)", :class => 'pull-right' %>
		</div>
		<div class="col-md-4">
			<%= f.collection_select(:technician_ids, Technician.all(:order => "email ASC"), :id, :full_name, {:selected => @ticket.technician_ids}, {:multiple => true}) %>
		</div>
	</div>
		
	<div class="row">	
		<div class="col-md-1">
			<%= f.label :description, "Description" %>
		</div>
		<div class="col-md-5">
			<%= f.text_area :description, :rows => 15, :class => 'form-control' %>
		</div>
		<p>&nbsp;</p>
		<div class="col-md-1 col-md-offset-1">
			<%= f.label :status, "Status", :class => 'pull-right' %>
		</div>
		<div class="col-md-4">
			<%= f.select(:status, Ticket::TICKET_STATUS) %>
		</div>
		<p>&nbsp;</p>
		<div class="col-md-1 col-md-offset-1">
			<%= f.label :deadline, "Deadline", :class => 'pull-right' %>
		</div>
		<div class="col-md-4">
			<%= f.date_select :deadline, {:include_blank => true, :default => nil} %>
		</div>
		<p>&nbsp;</p>
		<div class="col-md-1 col-md-offset-1">
			<%= f.label :priority, "Priority?", :class => 'pull-right' %>
		</div>
		<div class="col-md-4">
			<%= f.check_box :priority %>
		</div>
		<p>&nbsp;</p>
		<div class="col-md-2">
			<%= f.label :user_email, "User email", :class => 'pull-right field_label' %>
		</div>
		<div class="col-md-3">
			<%= f.text_field :user_email, data: {autocomplete_source: User.order(:email).map(&:email)}, :class => 'form-control' %>
		</div>
		<p>&nbsp;</p>
		<p>&nbsp;</p>
		<div class="col-md-1 col-md-offset-1">
			<%= f.label :asset_id, "Asset(s):", :class => 'pull-right' %>
		</div>
		<div class="col-md-4">
			<%= f.collection_select(:asset_ids, Asset.all(:order => 'tag_number ASC'), :id, :tag_number, {:selected => @ticket.asset_ids}, {:multiple => true}) %>
		</div>
	</div>
	<p>&nbsp;</p>
	<div class="row col-md-offset-1">
		<%= f.submit "Save Ticket", :class => 'btn btn-success' %>
	</div>	
<% end %>
<p>&nbsp;</p>

app/views/tickets/edit.html.erb
<h3 class="page-title"> Edit Ticket </h3>

<%= render "ticket_form" %>

<div class="row col-md-offset-1">
	<%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> back'.html_safe, ticket_url(@ticket) %>
</div>

app/views/tickets/index.html.erb
<!-- Tabbed Navigation !-->
<ul class="nav nav-tabs" id="myTab">
  <li class="active"><a href="#my_tickets"><span class="glyphicon glyphicon-tags"></span>&nbsp; My Tickets</span></a></li>
  <li><a href="#active"><span class="glyphicon glyphicon-time"></span>&nbsp; Active &nbsp;<span class="badge new-tickets-badge"><%= @new_tickets.count if @new_tickets.count > 0 %></span></a></li>
  <li><a href="#inactive"><span class="glyphicon glyphicon-inbox"></span>&nbsp; Inactive</a></li>
</ul>

<!-- Search Box -> Add Ticket Button !-->
<div class="list-group-item list-group-item-set-height">
	<%= form_tag tickets_path, :method => 'get', :id => "tickets_search" do %>
		<%= text_field_tag :search, params[:search], :autocomplete => 'off', :placeholder => 'Search Tickets...' %>
  <div class="pull-right"><%= link_to '<span class="glyphicon glyphicon-plus-sign add-ticket"></span>'.html_safe, new_ticket_path %></div>    	
</div>

<div class="tab-content">
<!-- Tab Content "My Tickets" !-->
  <div class="tab-pane active" id="my_tickets">
	  <% @my_tickets.each do |ticket| %>
	    <%= render "ticket", :ticket => ticket %>
    <% end %>
  </div>
  

<!-- Tab Content "Active" !-->
  <div class="tab-pane" id="active">
	  <% @active_tickets.each do |ticket| %>
	    	<%= render "ticket", :ticket => ticket %>
    <% end %>
  </div>
  
<!-- Tab Content "Inactive" !-->
  <div class="tab-pane" id="inactive">
	  <% @inactive_tickets.each do |ticket| %>
	    	<%= render "ticket", :ticket => ticket %>
    <% end %>
  <!-- Pagination !-->  
  <%= will_paginate @inactive_tickets %>
  </div>
  
  <% end %>
  
</div>

<!-- Javascript for persistant tabs !-->
<script>
	// cache the id
	var navbox = $('#myTab');
	// activate tab on click
	navbox.on('click', 'a', function (e) {
  	var $this = $(this);
		// prevent the Default behavior
		e.preventDefault();
		// set the hash to the address bar
		window.location.hash = $this.attr('href');
		// activate the clicked tab
		$this.tab('show');
	})

	// if we have a hash in the address bar
	if(window.location.hash){
  	// show right tab on load (read hash from address bar)
		navbox.find('a[href="'+window.location.hash+'"]').tab('show');
	}
	
  setTimeout(function() {
    window.location.reload();
  }, 600000);
</script>

app/views/tickets/index.js.erb
$("#my_tickets").html('<%= j render(@my_tickets) %>');
$("#active").html('<%= j render(@active_tickets) %>');
$("#inactive").html('<%= j render(@inactive_tickets) %>');

app/views/tickets/new.html.erb
<h3 class="page-title"> New Ticket </h3>

<%= render "ticket_form" %>

<div class="row col-md-offset-1">
	<%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> back'.html_safe, tickets_url %>
</div>

app/views/tickets/show.html.erb
<div class="col-md-12">
	<span class="title">
		<% if @ticket.id < 10 %>
			00<%= @ticket.id %>
		<% elsif @ticket.id >= 10 and @ticket.id < 100 %>
			0<%= @ticket.id %>
		<% else %>
			<%= @ticket.id %>
		<% end %>
		- <%= @ticket.title %>
	</span>
	
	<% if @ticket.priority == true %><span class="priority-show">Priority</span><% end %>
	
	<% if @ticket.status == "not started" %>
		<span class="label label-danger label-show"><%= @ticket.status %></span>
	<% elsif @ticket.status == "in progress" %>
		<span class="label label-success label-show"><%= @ticket.status %></span>
	<% elsif @ticket.status == "parts hold" %>
		<span class="label label-info label-show"><%= @ticket.status %></span>
	<% elsif @ticket.status == "client wait" %>
		<span class="label label-primary label-show"><%= @ticket.status %></span>
	<% elsif @ticket.status == "done" %>
		<span class="label label-default label-show"><%= @ticket.status %></span>
	<% end %>
	
	<% @ticket.technicians.each do |technician| %>
		<%= link_to image_tag(technician.avatar.url(:thumb), :class => 'img-circle border-show'), technician_url(technician) %>
	<% end %>
	
	<br>

<% if @ticket.deadline.nil? %>
<% else %>
	<% if @ticket.deadline < Date.today %>
		<span class="past-due">
			Deadline: <%= @ticket.deadline.to_s(:short) %>
		</span>
	<% else %>
		<span class="deadline">
			Deadline: <%= @ticket.deadline.to_s(:short) %>
		</span>
	<% end %>
<% end %>
</div>

<div class="col-md-12">
	<% if @ticket.user %>
		<%= link_to user_path(@ticket.user) do %>
			<%= render "users/user_tickets" %>
		<% end %>
	<% end %>
</div>

<div class="row">
	<div class="col-md-5"><hr></div>
</div>

<div class="col-md-12">
	<% if @ticket.attachments %>
		<% @ticket.assets.each do |asset| %>
			<%= render "assets/asset_tickets", :asset => asset  %>
		<% end %>
		<% else %>
			No asset assigned
	<% end %>
</div>

<div class="row col-md-12 description">Ticket Description:</div>
<div class="well well-sm col-md-9"><%= @ticket.description %></div>

<div class="row col-md-12 edit-btn">
	<%= link_to 'Edit Ticket', edit_ticket_path(@ticket), :class => 'btn btn-default' %>
</div>

<div class="row col-md-12 back-btn">
	<%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> back'.html_safe, root_url %>
</div>	
	
<div class="row col-md-12 description">Comments:</div>
<div class="row">&nbsp;</div>
	<%= render "comments/form" %>
<div class="row">
	<div class="col-md-9">&nbsp;</div>
</div>
	<%= render "comments/comments" %>