config/routes.rb
SpeedingTicketNew::Application.routes.draw do

  resources :purchases

	root to: 'tickets#index'
	
	get 'signup', to: 'technicians#new', as: 'signup'
	get 'login', to: 'sessions#new', as: 'login'
	get 'logout', to: 'sessions#destroy', as: 'logout'

  	resources :technicians
  	resources :sessions
  	resources :users do
  		resources :comments
  	end
  	resources :assets do
  		resources :comments
  	end
  	resources :tickets do
  		resources :comments
  	end
  	resources :purchases
  	resources :softwares

end

app/models/software.rb
class Software < ActiveRecord::Base

#Asssociations
	has_many :purchases
	has_many :installations
	has_many :assets, :through => :installations

#Validation
	validates_presence_of :title, :version_number, :manufacturer

#Definitions
	LICENSE_TYPE = ['', 'Single User License', 'Volume License', 'Licence Server (Network)', 'Site Licence', 'Perpetual License', 'USB Dongle', 'Open Source']

#Functions
  def full_title
		[title, version_number].join(' ')
	end

	def self.search(search)
  	if search
    	where('title LIKE ? OR manufacturer LIKE ? OR license_type LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%")
		else
    	scoped
		end
	end

end

app/controllers/softwares_controller.rb
class SoftwaresController < ApplicationController

before_filter :authorize, only: [:new, :create, :show, :edit, :update, :index]

#New Action
	def new
		@software = Software.new
	end
	
#Create Action	
	def create
		@software = Software.new(software_params)
		if @software.save
			redirect_to @software
		else
			render "new"
		end
	end

#Show Action	
	def show
    	@software = Software.find(params[:id])
	end

#Edit Action	
	def edit
    	@software = Software.find(params[:id])
	end

#Update Action	
	def update
		@software = Software.find(params[:id])
		if @software.update_attributes(software_params)
			redirect_to @software
		else
			render "edit"
		end
	end
	
#Index Action
	def index
		@software_list = Software.all.search(params[:search])
	end
	
#Private Actions	
private	
	def software_params
		params.require(:software).permit(:asset_id, :title, :version_number, :manufacturer, :license_type, :license_number)
    end

end

app/helpers/softwares_helper.rb
module SoftwaresHelper
end

app/views/softwares/_software.html.erb
<div class="list-group-item list-group-item-hover">
	<%= link_to software_path(software) do %>
		<div class="row">
			<div class="col-md-4">
				<strong><%= software.title %> <%= software.version_number %> </strong>
				<br>
				<%= software.manufacturer %> | <%= software.license_type %>
			</div>
		</div>
	<% end %>
</div>

app/views/softwares/_software_form.html.erb
<%= form_for @software do |f| %>
	<% if @software.errors.any? %>
		<div id='errorExplaination'>
			<h2><%= pluralize(@software.errors.count, "error") %> prohibited this software title from being saved:</h2>
			<ul>
			<% @software.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
		
	<div class="row">
		<div class="col-md-3">
			<%= f.label :title, "Software Title" %>
			<br>
			<%= f.text_field :title, :class => 'form-control' %>
		</div>
		<div class="col-md-1">
			<%= f.label :version_number, "Version" %>
			<br>
			<%= f.text_field :version_number, :class => 'form-control' %>
		</div>
	</div>
	
	<div class="row">&nbsp;</div>
	
	<div class="row">
		<div class="col-md-3">
			<%= f.label :manufacturer, "Manufacturer" %>
			<br>
			<%= f.text_field :manufacturer, :class => 'form-control' %>
		</div>
	</div>
		
	<div class="row">&nbsp;</div>
	
	<div class="row">
		<div class="col-md-3">
			<%= f.label :license_number, "License Number" %>
			<br>
			<%= f.text_field :license_number, :class => 'form-control' %>
		</div>
	</div>
	
	<div class="row">&nbsp;</div>
	
	<div class="row">
		<div class="col-md-3">
			<%= f.label :license_type, "License Type" %>
			<div class="styled-select-software">
				<%= f.select(:license_type, Software::LICENSE_TYPE) %>
			</div>
		</div>
	</div>
		
	<div class="row">&nbsp;</div>
	
	<div class="row">
		<div class="col-md-3">
			<%= f.submit "Save Software Title", :class => 'btn btn-success' %>
		</div>
	</div>
	
<% end %>

<div class="row">&nbsp;</div>
<div class="row">&nbsp;</div>

app/views/softwares/edit.html.erb
<h3 class="page-title"> Edit <%= @software.title %> </h3>

<%= render "software_form" %>

<div class="row col-md-12">
	<%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> back'.html_safe, software_url(@software) %>
</div>

app/views/softwares/index.html.erb
<h2> All Software Titles </h2>

<div class="list-group-item list-group-item-set-height">
	<%= form_tag softwares_path, :method => 'get', :id => "softwares_search" do %>
		<%= text_field_tag :search, params[:search], :autocomplete => 'off', :placeholder => 'Search Software...' %>
  <div class="pull-right"><%= link_to '<span class="glyphicon glyphicon-plus-sign add-ticket"></span>'.html_safe, new_software_path %></div>    	
</div>

<div id="software">
	<% @software_list.order('title ASC').each do |software| %>
		<%= render "software", :software => software  %>
	<% end %>
</div>
<% end %>

app/views/softwares/index.js.erb
$("#software").html('<%= j render(@software_list) %>');

app/views/softwares/new.html.erb
<h3 class="page-title"> New Software Title </h3>

<%= render "software_form" %>

<div class="row col-md-12">
	<%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> back'.html_safe, softwares_url %>
</div>

app/views/softwares/show.html.erb
<div class="row">
	<div class="col-md-12 user-info">
		<strong><%= @software.manufacturer %> <%= @software.title %> <%= @software.version_number %></strong>
		<br>
		<%= @software.license_type %><% if @software.license_number.present? %>: <%= @software.license_number %><% end %>
		<br>
		<%= link_to 'Edit software title', edit_software_path(@software), :class => 'btn btn-default btn-xs' %>
	</div>
</div>

<div class="row">&nbsp;</div>
<div class="row">&nbsp;</div>

<div class="row col-md-12 back-btn">
	<%= link_to '<span class="glyphicon glyphicon-arrow-left"></span> back'.html_safe, softwares_url %>
</div>	