config/routes.rb
SpeedingTicketNew::Application.routes.draw do

  resources :purchases

	root to: 'tickets#index'
	
	get 'signup', to: 'technicians#new', as: 'signup'
	get 'login', to: 'sessions#new', as: 'login'
	get 'logout', to: 'sessions#destroy', as: 'logout'

  	resources :technicians
  	resources :sessions
  	resources :users do
  		resources :comments
  	end
  	resources :assets do
  		resources :comments
  	end
  	resources :tickets do
  		resources :comments
  	end
  	resources :purchases
  	resources :softwares

end

app/models/asset.rb
class Asset < ActiveRecord::Base

#Asssociations
	belongs_to :user
	has_many :purchasings
	has_many :purchases, :through => :purchasings
	has_many :installations
	has_many :softwares, :through => :installations
	has_many :attachments
	has_many :tickets, :through => :attachments
	has_many :comments, as: :commentable
	has_paper_trail :on => [:create, :update],
					:only => [:user_id, :location, :asset_name, :serial_number, :mac_address1, :mac_address2, :mac_address3]

#Validation
	validates_presence_of :location, :tag_number, :asset_type, :asset_name, :model, :serial_number, :manufacturer
	validates_uniqueness_of :tag_number, :serial_number
	validates_uniqueness_of :mac_address1, :allow_blank => true
	
#Definitions
	ASSET_TYPE = ['', 'Apple Laptop', 'Apple Desktop', 'Windows Laptop', 'Windows Desktop', 'iPad', 'Windows Tablet', 'iPod', 'Monitor', 'External HDD', 'Server', 'Linux PC', 'Apple TV', 'Camera', 'Loud Speakers', 'Projector', 'Television', 'Video Equiptment', 'Printer', 'Network Device']
	
	
#Methods
	def user_email
  	user.try(:email)
	end

	def user_email=(email)
 	 self.user = User.find_by_email(email) if email.present?
 	end
 	
 	def self.search(search)
  	if search
   	 Asset.joins(:user).where('assets.location LIKE ? OR tag_number LIKE ? OR asset_type LIKE ? OR asset_name LIKE ? OR model LIKE ? OR serial_number LIKE ? OR mac_address1 LIKE ? OR mac_address2 LIKE ? OR mac_address3 LIKE ? OR users.first_name LIKE ? OR users.last_name LIKE ? OR users.email LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
	 	else
    	scoped
		end
	end
	
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base

#Associations
	belongs_to :technician
	belongs_to :ticket

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base

#Associations
	belongs_to :asset
	belongs_to :ticket

end

app/models/comment.rb
class Comment < ActiveRecord::Base

#Associations
	belongs_to :commentable, polymorphic: true
	belongs_to :technician

end

app/models/installation.rb
class Installation < ActiveRecord::Base

	belongs_to :asset
	belongs_to :software

end

app/models/purchase.rb
class Purchase < ActiveRecord::Base

#Associations
	belongs_to :software
	belongs_to :user
	has_many :purchasings
	has_many :assets, :through => :purchasings
	
#Validation
	validates_presence_of :user_id, :account_number, :quantity

#Definitions
	PURCHASE_STATUS = ['New', 'Open', 'Closed']

#Methods
	def user_email
  	user.try(:email)
	end

	def user_email=(email)
 	 self.user = User.find_by_email(email) if email.present?
 	end
 	
	def self.search(search)
  	if search
    	Purchase.joins(:user).where('item_name LIKE ? OR part_number LIKE ? OR account_number LIKE ? OR users.first_name LIKE ? OR users.last_name LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
		else
    	scoped
		end
	end

end

app/models/purchasing.rb
class Purchasing < ActiveRecord::Base
	belongs_to :purchase
	belongs_to :asset
end

app/models/software.rb
class Software < ActiveRecord::Base

#Asssociations
	has_many :purchases
	has_many :installations
	has_many :assets, :through => :installations

#Validation
	validates_presence_of :title, :version_number, :manufacturer

#Definitions
	LICENSE_TYPE = ['', 'Single User License', 'Volume License', 'Licence Server (Network)', 'Site Licence', 'Perpetual License', 'USB Dongle', 'Open Source']

#Functions
  def full_title
		[title, version_number].join(' ')
	end

	def self.search(search)
  	if search
    	where('title LIKE ? OR manufacturer LIKE ? OR license_type LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%")
		else
    	scoped
		end
	end

end

app/models/technician.rb
class Technician < ActiveRecord::Base

#Associations
	has_many :comments
	has_many :assignments
	has_many :tickets, :through => :assignments

#Validation
	validates_presence_of :first_name, :last_name, :email
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
	validates_uniqueness_of :email
	
#Attachements
	has_secure_password
	has_attached_file :avatar, :styles => { :medium => "100x100>", :thumb => "32x32>" }, :default_url => "/images/:style/missing.png"

#Generate authorization token before creating user
	before_create {generate_token(:auth_token)}

#Functions
    def full_name
		[first_name, last_name].join(' ')
	end
	
	def generate_token(column)
		begin
			self[column] = SecureRandom.urlsafe_base64
		end while Technician.exists?(column => self[column])
	end
	
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base

#Asssociations
	belongs_to :user 
	has_many :assignments
	has_many :technicians, :through => :assignments
	has_many :attachments
	has_many :assets, :through => :attachments
	has_many :comments, as: :commentable

#Validation
	validates_presence_of :description

#Definitions
	TICKET_STATUS = ['not started', 'in progress', 'parts hold', 'client wait', 'done']
	
#Methods
	def user_email
  	user.try(:email)
	end

	def user_email=(email)
 	 self.user = User.find_by_email(email) if email.present?
 	end

 	def self.search(search)
  	if search
   	 Ticket.joins(:user).where('title LIKE ? OR description LIKE ? OR users.first_name LIKE ? OR users.last_name LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
	 	else
    	scoped
		end
	end

end

app/models/user.rb
class User < ActiveRecord::Base

#Associations
	has_many :assets 
	has_many :tickets
	has_many :purchases
	has_many :comments, as: :commentable

#Validation
	validates_presence_of :first_name, :last_name, :email, :location, :department
	validates_uniqueness_of :email
	validates :email, :email => true
	validates :phone_number, :length => { :minimum => 6, :maximum => 12 }, :allow_blank => true

#Attachments	
    has_attached_file :avatar, :styles => { :medium => "100x100>", :thumb => "32x32>" }, :default_url => "/images/:style/missing.png"
    
#Definitions
	DEPARTMENT = ['ADPR', 'BCS', 'COMM', 'CSD', 'DEAN', 'JRN', 'TISM' ]
    
#Functions
  def full_name
		[first_name, last_name].join(' ')
	end
	
	def self.search(search)
  	if search
   	 User.where('first_name LIKE ? OR last_name LIKE ? OR email LIKE ? OR location LIKE ? OR phone_number LIKE ? OR department LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
	 	else
    	scoped
		end
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/softwares_helper.rb
module SoftwaresHelper
end

app/helpers/technicians_helper.rb
module TechniciansHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpeedingTicketNew</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<buton type="button" class="navbar-toggle" data-togle="collapse" data-target=".navbar-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</buton>
			<% if current_technician.nil? %>
				<%= link_to "TinRooster 1.0", login_url, :class => 'navbar-brand' %>
			<% else %>
				<%= link_to "TinRooster 1.0", root_url, :class => 'navbar-brand' %>
		</div>
		<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li><%= link_to '<span class="glyphicon glyphicon-dashboard"></span> Dashboard'.html_safe, root_url %></li>
				<li><%= link_to '<span class="glyphicon glyphicon-user"></span> Users'.html_safe, users_url %></li>
				<li><%= link_to '<span class="glyphicon glyphicon-hdd"></span> Assets'.html_safe, assets_url %></li>
				<li><%= link_to '<span class="glyphicon glyphicon-wrench"></span> Technicians'.html_safe, technicians_url %></li>
				<li><%= link_to '<span class="glyphicon glyphicon-book"></span> Software'.html_safe, softwares_url %></li>
				<li><%= link_to '<span class="glyphicon glyphicon-credit-card"></span> Purchases'.html_safe, purchases_url %></li>
				<li><%= link_to '<span class="glyphicon glyphicon-list"></span> Wiki'.html_safe, root_url %></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= image_tag current_technician.avatar.url(:thumb), :class => 'img-circle border' %> <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><%= link_to 'Account', technician_path(@current_technician.id) %></li>
						<li><%= link_to 'Logout', logout_path %></li>
					</ul>
				</li>
			</ul>
			<% end %>
		</div>
	</div>
</div>

<div class="container">

<div class="alert-message" >
    <% if flash[:notice] %>
    	<div class="alert alert-info">
        	<a class="close" data-dismiss="alert">×</a>
			<stong><%= flash[:notice] %></strong>
		</div>
    <% elsif flash[:alert] %>
    	<div class="alert alert-warning">
        	<a class="close" data-dismiss="alert">×</a>
			<stong><%= flash[:alert] %></strong>
        </div>
    <% end %>
</div>


<%= yield %>

<footer>
	<hr>
    <p><abbr title="Tin Rooster 1.0">College of Communication Arts & Sciences</abbr> &copy; 2014</p>
</footer>

</div>

</body>

<script>
	$(".alert").alert();
	window.setTimeout(function() { $(".alert").alert('close'); }, 2000);
</script>


</html>